# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4966e1046fa379926ec9519831f79b28a72ed0ef6aa18a7f12463f336dfa9fcb538f31ee44c664955619cb355da3b2d66e6c1d088ac3995a3dc770ea300b93c9

test:
  secret_key_base: e7a529f833e887d2fa2316e9c92c71aa2ea4803e0eab2895381b3682d9cf2b1412b0ee8feced410266ab9a4aa1cd2cde66b610f2528904df6a86958fa102c077

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
